
import "./globals.css";
import { Montserrat } from "next/font/google";

const Mont = Montserrat({
 subsets: ["latin"],
 weight: ['500', '300', '600'],
});

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Mont.className}`}>{children}</body>
    </html>
  );
}
